from .softmax_focal_loss import SoftmaxFocalLoss
from .task_aligned_focal_loss import TaskAlignedFocalLoss
from .binary_kl_div_loss import BinaryKLDivLoss
from .soft_label_focal_loss import FocalKLLoss